---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq
  namespace: {{.namespace}}
  labels:
    app: rabbitmq
    component: rabbitmq
    role: services
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rabbitmq
  namespace: {{.namespace}}
  labels:
    app: rabbitmq
    component: rabbitmq
    role: services
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rabbitmq
  namespace: {{.namespace}}
  labels:
    app: rabbitmq
    component: rabbitmq
    role: services
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rabbitmq
subjects:
- kind: ServiceAccount
  name: rabbitmq
