---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-management
  namespace: {{.namespace}}
  labels:
    app: rabbitmq
    component: rabbitmq
    role: services
spec:
  ports:
  - name: http
    port: 15672
  selector:
    app: rabbitmq
    component: rabbitmq
    role: services
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
  namespace: {{.namespace}}
  labels:
    app: rabbitmq
    component: rabbitmq
    role: services
spec:
  clusterIP: None
  ports:
  - name: tcp-amqp
    port: 5672
  - name: tcp-epmd
    port: 4369
  - name: tcp-dist
    port: 25672
  selector:
    app: rabbitmq
    component: rabbitmq
    role: services
