---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: {{.namespace}}
  labels:
    app: vault
    component: vault
    role: services
spec:
#   type: LoadBalancer
{{if .vault_init}}
  loadBalancerIP: {{.lb.ip}}
{{end}}
  ports:
  - name: http
{{if .vault_init}}
    port: 443
{{else}}
    port: 8200
{{end}}
    targetPort: 8200
  selector:
    app: vault
    component: vault
    role: services
