
---
apiVersion: v1
kind: Namespace
metadata:
  name: local
  labels:
    istio-injection: enabled
---
kind: Service
apiVersion: v1
metadata:
  name: beamery
  namespace: local
spec:
  ports:
  - name: http
    port: 1234
  selector:
    component: mongo
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
  namespace: local
  labels:
    component: mongo
spec:
  serviceName: mongo
  replicas: 1
  template:
    metadata:
      labels:
        component: mongo
    spec:
      containers:
      - name: mongo
        image: alpine
        command:
        - "/bin/sh"
        - "-c"
        - >
          while true; do sleep 1; done
